const mongoose=require("mongoose");

const participantSchema=new mongoose.Schema({
    teamName:{
        type:String,
        required:true
    },
    referral:{
        type:String
    },
    domain:{
        type:String,
        required:true
    },
    teamSize:{
        type:Number,
        required:true
    },
    leadName:{
        type:String,
        required:true
    },
    leadEmail:{
        type:String,
        required:true
    },
    leadMobile:{
        type:String,
        required:true
    },
    leadClg:{
        type:String,
        required:true
    },
    m1Name:{
        type:String,
        required:true
    },
    m1Email:{
        type:String,
        required:true
    },
    m1Mobile:{
        type:String,
        required:true
    },
    m1Clg:{
        type:String,
        required:true
    },
    m2Name:{
        type:String,
    },
    m2Email:{
        type:String,
    },
    m2Mobile:{
        type:String,
    },
    m2Clg:{
        type:String,
    },
    m3Name:{
        type:String,
    },
    m3Email:{
        type:String,
    },
    m3Mobile:{
        type:String,
    },
    m3Clg:{
        type:String,
    },
},{timestamps:true});

module.exports=mongoose.model("Participant",participantSchema);